### ISSUE TITLE
Not all selections listed for conditions

### ISSUE THREAD

**Issue by MattunR** [BattleScribe/Release#1]
In 2.01.09, I still have the issue listed here: battlescribe.uservoice.com/forums/55066-general/suggestions/19824823-bug-in-data-editor-condition, i.e.: if I have (in my case) a Set Hidden modifier, If Equal to 0 Selections of X, then when selecting X I can only select a very limited amount of stuff. What I want is to select a unit, but no units at all can be selected. I can type in the Unique ID and the right unit will be listed, but it won't work (still says NO CHILD).

**Comment by Jonskichov** [comment]
Fixed in 2.01.10
