### ISSUE TITLE
New Shared Rule appears under Shared Selection Entries node

### ISSUE THREAD

**Issue by morvael** [BattleScribe/Release#10]
As the title says. Happen on latest v2.01.11.104.

Reported first on Reddit: https://www.reddit.com/r/BattleScribe/comments/8e4wq6/new_shared_rules_added_to_shared_selection_entries/

**Comment by morvael** [comment]
After fresh load rule appears in correct place, only when it is added it shows up under wrong node.

**Comment by Jonskichov** [comment]
Fixed in 2.01.12.105
