### ISSUE TITLE
v2.03 bug: condition not triggered for nested/child selections (regression)

### ISSUE THREAD

**Issue by amis92** [BattleScribe/Release#100]
Repro set (gst, cat and ros) works (reproduces) on PC v2.03.07.135, newest at the time of writing.

[Drone PL issue repro.zip](https://github.com/BattleScribe/Release/files/3851847/Drone.PL.issue.repro.zip)

Repro visuals:

PL cost of both teams should be 3PL
![image](https://user-images.githubusercontent.com/2671396/68949927-66036a00-07bb-11ea-80f4-af2eb1027e28.png)

This is the condition that doesn't work correctly:
![image](https://user-images.githubusercontent.com/2671396/68949998-8df2cd80-07bb-11ea-9df6-73a9ed7a42c6.png)

(same for Strike Team)

The interesting part is that it works for the MV36 Drone which is a direct child of the Drones group, but the children of the nested Tactical Drones group don't trigger the condition.

I'm pretty sure it worked in previous versions.

Original report: https://github.com/BSData/wh40k/issues/5949

**Comment by Jonskichov** [comment]
Fixed in iOS 2.03.05.140 (awaiting Apple review)

**Comment by amis92** [comment]
@Jonskichov and what version for PC/Android is the fix in?

'Cause it kind of looks like a copy-paste message from all the other issues already fixed in PCv2.03.07.135 - and *this* happens on that version as well.

**Comment by Jonskichov** [comment]
Fixed in:
Android: 2.03.13.321
Desktop: 2.03.08.136
(Might have been the previous versions? I forget ;))

This issue came up just after I'd pushed an Android/Desktop release, but before the iOS release, hence the fix made it into iOS first.
