### ISSUE TITLE
Bug: Roster Editor - Alerts duplicating themselves

### ISSUE THREAD

**Issue by cartag** [BattleScribe/Release#101]
We are seeing cases of errors duplicating many times when trying to build a roster for AoS. Below is a thread that has screenshots. It is also not verifying that the item has been selected. It's set up the same as other AoS files, the Khorne one exhibits the same behavior. 

https://github.com/BSData/warhammer-age-of-sigmar/issues/1121

**Comment by cartag** [comment]
https://github.com/BSData/warhammer-age-of-sigmar/issues/1118

**Comment by cartag** [comment]
Also, this is only on PC, Windows verified so far. Does not exist on iOS, unsure about Android.

**Comment by OftKilted** [comment]
This issue did not exist in 2.03.01, but is broken in anything after.

**Comment by Jonskichov** [comment]
Cheers guys, found and fixed the issue. I'll get a new release out soon.

**Comment by Jonskichov** [comment]
Fixed in:
Android: 2.03.13.321
Desktop: 2.03.08.136
iOS: I'm working on it

**Comment by Jonskichov** [comment]
Fixed in:
iOS: 2.03.06.141
