### ISSUE TITLE
Not verifying Min 1 in Roster (at least) in upgrades

### ISSUE THREAD

**Issue by cartag** [BattleScribe/Release#103]
We're having an issue where it is not registering that options are picked for model selections. 

![image](https://user-images.githubusercontent.com/4388344/69359311-a0e72100-0c45-11ea-9213-0fe357d3f748.png)

![image](https://user-images.githubusercontent.com/4388344/69359410-c6742a80-0c45-11ea-94d1-bae8391e5b63.png)

It's set up the exact same way in all the other data files and has been working in the past, it may be another recent bug.

**Comment by Jonskichov** [comment]
Hmm, it looks like this might have been an issue for some time. Do you have any idea of when (if ever) this was working?

**Comment by cartag** [comment]
It's worked on PC for a long while, almost all catalogs are set up with that logic for the mandatory artefacts from the subfactions. I haven't done much in the way of army list building, but I do know it has worked since categories were introduced.

**Comment by Jonskichov** [comment]
~Fixed in:
Android: 2.03.15.323
Desktop: 2.03.09.137
iOS: Pending~

**Comment by cartag** [comment]
Confirmed resolved in 2.03.09.137

**Comment by Jonskichov** [comment]
Relates to https://github.com/BattleScribe/Release/issues/105

**Comment by Jonskichov** [comment]
Fixed in:
Android: 2.03.16.325
Desktop: 2.03.10.139
iOS: Pending

**Comment by Jonskichov** [comment]
Fixed in:
iOS: 2.03.06.141
