### ISSUE TITLE
Max in Roster not counting beyond instances of the same parent

### ISSUE THREAD

**Issue by GenWilhelm** [BattleScribe/Release#104]
Example: Tyranids catalogue from Warhammer 40,000
![image](https://user-images.githubusercontent.com/22036809/69386818-97000500-0cbb-11ea-8d87-a848ccd9d3b3.png)

With just a Warlord, I should only be allowed to pick a single Bio-artefact, but it only flags an error if I put them on instances of the same selection.

**Correct behaviour:**
![image](https://user-images.githubusercontent.com/22036809/69386930-04139a80-0cbc-11ea-88ee-39384eb0e753.png)

**Incorrect behaviour:**
![image](https://user-images.githubusercontent.com/22036809/69386947-1d1c4b80-0cbc-11ea-81d2-f626778e0323.png)

**Comment by Jonskichov** [comment]
Fixed in:
Android: 2.03.15.323
Desktop: 2.03.09.137
iOS: Pending

**Comment by Jonskichov** [comment]
Fixed in:
iOS: 2.03.06.141
