### ISSUE TITLE
Min in Parent not working

### ISSUE THREAD

**Issue by Tigerwraith** [BattleScribe/Release#105]
Jon seems Min in Parent is now not working in BS 2.03.15 on android and 2.03.09 on PC
![Annotation 2019-11-24 123604](https://user-images.githubusercontent.com/39889736/69499370-0ee64f00-0eb7-11ea-9ba3-6db51ebf7613.png)

In the pic, Heavy Stubber is selected by default, but it still gives the error that we need one. If you change it to the Melta, it does not change.

**Comment by Jonskichov** [comment]
🤦‍♂️

Thanks, I'll get it sorted.

**Comment by Jonskichov** [comment]
Fixed in:
Android: 2.03.16.325
Desktop: 2.03.10.139
iOS: Pending

**Comment by Tigerwraith** [comment]
Yay

**Comment by Jonskichov** [comment]
Fixed in:
iOS: 2.03.06.141
