### ISSUE TITLE
If Equal to X selections in Force conditions not triggering

### ISSUE THREAD

**Issue by Mad-Spy** [BattleScribe/Release#106]
Example in https://github.com/BSData/wh40k/blob/master/Chaos%20-%20Questor%20Traitoris.cat

The two "If Equal to X in Force conditions on the Shared Selection Entry below are not being triggered
![image](https://user-images.githubusercontent.com/29306451/70058093-32577b00-15d6-11ea-8eb6-e8ede592fa5e.png)

Links to Corrupted Heirloom attached to Root Selection Entries are not being correctly hidden, nor is the maximum allowed in the Force incremented.

**Comment by afraeve** [comment]
I'm seeing the same in various Epic Armageddon cats. Modifiers on shared selection entries don't respond if they refer to root entries. Couple of examples below:

https://github.com/BSData/wh40k-epic-armageddon/blob/master/Eldar%20-%20Lugganath%20-%20EA.cat
![Lugganath](https://user-images.githubusercontent.com/13020665/70182909-b09e4500-16dc-11ea-96c9-9fe9d5e74052.jpg)

https://github.com/BSData/wh40k-epic-armageddon/blob/master/Chaos%20-%20Alpha%20Legion%20-%20EA.cat
![AlphaLegion](https://user-images.githubusercontent.com/13020665/70182922-b85de980-16dc-11ea-8b5b-6debfd0e5454.jpg)

**Comment by Jonskichov** [comment]
Fixed in:
Desktop: 2.03.11.140
Android: 2.03.17.326
iOS: 2.03.09.144 (pending Apple approval, should be available soon)
