### ISSUE TITLE
[Regression] 2.03.11 - constraint on entry link stopped working

### ISSUE THREAD

**Issue by amis92** [BattleScribe/Release#107]
A constraint placed on a link doesn't seem to work, confirmed working in 2.03.10-PC.

Data used: 
[wh40k-xv9-repro.zip](https://github.com/BattleScribe/Release/files/3992939/wh40k-xv9-repro.zip)

Repro steps:
1. Create roster for T'au
2. Add XV9 (Elites)
3. Select 2 support systems for one model

Results:
2.03.10 - warning: xv9 has too many support systems (contraint: max 1 in parent)
2.03.11 - no warnings

**Comment by amis92** [comment]
2.03.17.326 on Android also displays similar behavior (ignoring constraints)

**Comment by cartag** [comment]
It's happening hit-or-miss in AoS files as well. It will obey or ignore constraints without any cause that I can find. 

I opened the .CAT in Notepad++ and the text strings used for an entry that does work and an entry that doesn't work both appeared the same.

**Comment by amis92** [comment]
40k awaits resolution at https://github.com/BSData/wh40k/issues/6672 :)

**Comment by Jonskichov** [comment]
Fixed in:
Desktop 2.03.12.141
Android 2.03.18.327
iOS 2.03.10.145 (pending Apple review)
