### ISSUE TITLE
Numbers not updating and text gets cut off

### ISSUE THREAD

**Issue by L3610N115** [BattleScribe/Release#110]
I got some weird issue where my BS doesn't update point costs or model count.

https://cdn.discordapp.com/attachments/550296225044234240/651896849073963018/unknown.png

I selected 34 Corsairs but it does not update anything until I click the value that it should update. So if I click the 22xCorsairs, it will update to 34.
It also cuts of some of the text for some reason, as you can see when you look at the point cost for the roster. It cuts off and says "..."

The Screenshot is from version 2.03.10 but the issue is still present in version 2.03.11

**Comment by ddarz** [comment]
Issue still present in 2.03.12

**Comment by Jonskichov** [comment]
Fixed for the next release

**Comment by Jonskichov** [comment]
Fixed in:
Desktop: 2.03.13.142
Android: 2.03.19.328
iOS: 2.03.11.147
