### ISSUE TITLE
[Roster Editor] Keyword issues

### ISSUE THREAD

**Issue by cartag** [BattleScribe/Release#114]
Current behavior of BS is to load a unit entirely before checking modifiers. The Add/Remove/Set modifier needs to be figured before the unit is loaded. The screenshot below should (and does) add the KHORNE keyword to the Daemon Prince. 

![image](https://user-images.githubusercontent.com/4388344/72014352-ec1cb980-321c-11ea-824c-e475b0d25ddb.png)

![image](https://user-images.githubusercontent.com/4388344/72014465-238b6600-321d-11ea-9e2d-501c6abcea00.png)

If I add the KHORNE keyword to the unit at root level (same thing the modifier should do) it now works properly. 

![image](https://user-images.githubusercontent.com/4388344/72014536-4cabf680-321d-11ea-8a0c-b6829fedb985.png)

**Comment by Thairne** [comment]
Adding a category to an entry via adding it by either addCategory or adding another entry that has the category does not trigger modifiers like hiding
e.g. "Dark Angels Master in Phobos Armour" gets the "Faction: Deathwing" keyword via "Stratagem: Inner Circle" selection which adds "Faction: Deathwing". Does not unhide the SEG "Warlord Traits: Deathwing" which unhides on the presence of "Faction: Deathwing"

**Comment by Mad-Spy** [comment]
@cartag, as a workaround, you should be able to add the KHORNE keyword to the selection under Mark of Chaos? It still shows as the model's keyword. That is how I have it working in the 40k Daemon Princes.

You can then show/hide the list/item by using "If Equal to 0 Selections in Parent of KEYWORD" conditions

**Comment by cartag** [comment]
@Mad-Spy the Mark of Chaos in the first pic has the keywords in it, but it doesn't propagate down to where an Ancestor check will work. The lists are nested so a parent check won't work. "If Ancestor instance of KHORNE" doesn't register.

**Comment by Jonskichov** [comment]
Fixed in:
Desktop: 2.03.13.142
Android: 2.03.19.328
iOS: 2.03.11.147
