### ISSUE TITLE
Show remaining points to spend

### ISSUE THREAD

**Issue by BitPsycho** [BattleScribe/Release#116]
The roster info currently shown in the right upper corner could be a bit better in my opinion.

Here are a couple of suggestions:

- Move it to the left corner as it is mostly used to see what points are occupied and based upon that units are chosen ... which are on the left side as well.
- The info should show how many points are still left to use ... now it only informs how many there are already used ... We can all do math but it would be much better that the info just shows how many there are left to choose from as well
- Do not display the roster info in red when the selection is still belove the roster total - red indicates a negative sentiment ( at least in western culture ) - why not use 3 colors - orange when still below, green when the roster matches and red when the amount is surpassed.
- It would also be nice if the font size is a bit bigger ...

**Comment by Jonskichov** [comment]
Some of this will be addressed in the upcoming desktop rebuild.

I like the idea of showing remaining points to spend. I'll see what I can do.

**Comment by Jonskichov** [comment]
This is mostly addressed (or no longer relevant) in the new desktop version.

I'm not sure "points remaining" really adds much to be honest.
