### ISSUE TITLE
Roster Points Discrepancy in Calculation on IOS v.s. Desktop

### ISSUE THREAD

**Issue by OftKilted** [BattleScribe/Release#117]
Issue:
Points validation is not the same on desktop (v 2.03.11) and IOS (Current Release v 2.03.09)

Noted in Kill Team ( https://github.com/BSData/wh40k-killteam ) Heretic Astartes Catalog v16.

Create Roster in Desktop with one Non-Specialist Terminator.
Add Chainfist. (6 points)
Points for model should be at 35 points.
Save Roster and then transfer it to IOS device, open the roster.
Points for Chainfist are now 0.

This may relate to:
https://battlescribe.uservoice.com/forums/55066-battlescribe/suggestions/39249682-bug-ios-point-values-of-referenced-entry-links-a

Included Zipped copy of example test roster.
[Heretic Astartes v16 Test.rosz.zip](https://github.com/BattleScribe/Release/files/4087556/Heretic.Astartes.v16.Test.rosz.zip)

Note: This does not appear on the current Android version of Battlescribe.

**Comment by Jonskichov** [comment]
Fixed in:
iOS 2.03.10.145 (pending Apple review)
