### ISSUE TITLE
Ability to Add Items In Catalogue Under Items in Game System

### ISSUE THREAD

**Issue by jmatchett** [BattleScribe/Release#119]
Was wanting to put in a feature request to see if we could ever get the ability to add items while within a catalogue to an item that exists within the game system.

For instancing putting a rule that applies to all leaders I put in the game system like so...
![Screen Shot 2020-02-15 at 9 20 41 AM](https://user-images.githubusercontent.com/5528542/74590626-b0bc9a00-4fd5-11ea-821b-8579666427ad.png)

But when in a catalogue for a specific faction, if that faction has a rule for their leaders you are unable to add anything to it as it is disabled in the catalogue...
![Screen Shot 2020-02-15 at 9 22 43 AM](https://user-images.githubusercontent.com/5528542/74590644-cd58d200-4fd5-11ea-89e4-d238c665e08f.png)

This would help keep the game system file cleaner and allowing faction specific items to stay within the faction catalogue.

**Comment by Jonskichov** [comment]
Unfortunately this is unlikely to happen in the foreseeable future. Technically this is possible, but would require a large amount of work and a lot of thought about how these kinds of things are stored in the data files.

It's possible I'll get around to it sometime, but don't hold your breath.

**Comment by Jonskichov** [comment]
Dupicate of: https://github.com/BattleScribe/Release/issues/131
