### ISSUE TITLE
Issue editing Roster Name (2.01.13.106)

### ISSUE THREAD

**Issue by CrusherJoe** [BattleScribe/Release#12]
When attempting to edit the Roster Name, I am only able to edit one character/keystroke before the box loses focus and I have to re-select it with the mouse. 

As in:
Press any letter-key, lose focus. Space bar, lose focus. Delete key, lose focus.

**Comment by amis92** [comment]
If you type super-fast, you can get up to 4 chars :D Checked on Windows.

**Comment by Jonskichov** [comment]
Fixed in 2.01.14.107
