### ISSUE TITLE
Android times out on loading roster

### ISSUE THREAD

**Issue by amis92** [BattleScribe/Release#120]
Not much info though: https://github.com/BSData/wh40k/issues/6745

Excerpt:
>Everytime I open a roster file it takes forever to load. Then times out and gives me a Battlescribe timed out notification. I have been a supporter for years. I have never had such a problem with Battlescribe. I have uninstalled and deleted the repositories then reinstalled it to no avail. Please help

**Comment by Jonskichov** [comment]
Not enough info really. I am going to assume they're opening a large file that their phone can't handle.

I've got some ideas for more optimisations, but of course YMMV...
