### ISSUE TITLE
Modifiers not working if constraints exist

### ISSUE THREAD

**Issue by Jonskichov** [BattleScribe/Release#121]
1. create roster (Patrol Det.)
2. add Commander in XV8
3. Mark him as Warlord
4. Select "Cross-linked stabiliser jets" from SigSystems & ProtoWeaponSystems

Now there are no warnings about that, you have the item, all is fine.

Open Data Editor, find Shared Selection Entry Group called Prototype Weapons Systems:
1. remove the constraint of max 1 in Parent (since it shouldn't actually be there per the rules)
2. repeat steps above to create a roster (or reload roster).
3. Observe there are no Prototype Weapons Systems visible in Commander.

**Comment by amis92** [comment]
Also I think number 2 only happens for some reason when you add another detachment, either before the SHAD or after. SHAD alone works fine, I think.

**Comment by Jonskichov** [comment]
Fixed in:
Desktop: 2.03.13.142
Android: 2.03.19.328
iOS: 2.03.11.147
