### ISSUE TITLE
Modifier groups are not applied consistently with separate modifiers in the Roster Editor UI

### ISSUE THREAD

**Issue by Mad-Spy** [BattleScribe/Release#122]
![image](https://user-images.githubusercontent.com/29306451/74649484-8efb1880-5177-11ea-9fc2-d05cde20e948.png)

That the above sets of modifiers should and do result in the same outcome, namely that if a "Pair of Lightning Claws" is selected, the Bolt Pistol group and Chainsword... group should not allow any selections and give a validation error.

However, the display of this in the Roster Editor UI is inconsistent.

![image](https://user-images.githubusercontent.com/29306451/74649774-25c7d500-5178-11ea-9c96-535aad318621.png)

The modifier group version does not provide the option to set the Bolt Pistol group to "None"; I have to delete the selection instead.

I think these should have the same display in the UI.

**Comment by Jonskichov** [comment]
@Mad-Spy Can you tell me what roster to make and what I need to add to it to make the error happen? I have no idea what I'm looking at :D

**Comment by Mad-Spy** [comment]
I took it out from the actual data because it didn't work properly. I've made a mockup below so you can see what I mean.

https://drive.google.com/file/d/1RUH8bS2BiaQq_RnDYPT-fDcN5fTv5Tnf/view?usp=sharing

There's no way to select "None" when using a modifier group to change the constraints.

**Comment by Jonskichov** [comment]
Fixed in:
Desktop: 2.03.13.142
Android: 2.03.19.328
iOS: 2.03.11.147
