### ISSUE TITLE
Modifiers should not be able to have an out-of-scope child

### ISSUE THREAD

**Issue by cartag** [BattleScribe/Release#123]
These one unit will change primary category of another unit to grant Battleline status when it is a general. 

![image](https://user-images.githubusercontent.com/4388344/74787048-694f3b80-526b-11ea-8f6b-d6579d670d55.png)

![image](https://user-images.githubusercontent.com/4388344/74786983-4a50a980-526b-11ea-9881-17182e78ab0b.png)

The first screenshot is for the unit that is inside of a battalion, the second is outside of it. The links both trace back to the same SSE.

**Comment by Jonskichov** [comment]
Your modifier is referencing the wrong "general". You want to point it at the shared one (under SSE) and not the "general" entry on the Skullmaster (since this one is not "visible" to the bloodcrushers).

That said, I should prevent unusable targets being available to modifiers.

**Comment by cartag** [comment]
The modifier is referencing the correct one. Behavior works as expected if it is outside of the battalion, the same logic works both inside and outside of battalions for a Tzeentch setup (Fateskimmer making Burning Chariots battleline). If I referenced the SSE general, it would trigger regardless of who the general is. Setting it to the General entry under Skullmaster only triggers off of that particular instance of it.

**Comment by cartag** [comment]
Here's the Tzeentch one that works both inside and outside of a battalion:
![image](https://user-images.githubusercontent.com/4388344/74969532-fa442500-53d9-11ea-8b6d-d65979a07ea8.png)

And the Khorne one that isn't working. 
![image](https://user-images.githubusercontent.com/4388344/74969584-11831280-53da-11ea-9c33-bdacd969dab1.png)

**Comment by cartag** [comment]
If you remove the ability to check for an upgrade on an SSE, it will break the vast majority of AoS catalogs and probably a lot of 40k as well.

**Comment by cartag** [comment]
I should probably also note that the General both link to is not a link to the SSE, but a separate General entry created for each unit (Fateskimmer/Skullmaster)

**Comment by Mad-Spy** [comment]
@cartag, the entries in your Fateskimmer and Skullmaster are different, which is why you are seeing different behaviour.

The Fateskimmer entry is a discrete Selection Entry so it has its own ID. The Skullmaster one is a link, so BS collapses it to the linked ID when it constructs the dataset in the Roster Editor.

You are correct that this used to work and you could reference link IDs in Modifiers, but that functionality was lost several versions ago. We _did_ have to do a bunch of work in 40k to work around it.

You'll either have to create a unit-specific General entry, like there is in the Fateskimmer, or create a BLOODMASTER category (which the unit should have anyway?) and validate off of that.

**Comment by cartag** [comment]
Skullmaster isn't a link, it's a separate entry. 
![image](https://user-images.githubusercontent.com/4388344/74978231-69754580-53e9-11ea-853b-42303d6ce161.png)
![image](https://user-images.githubusercontent.com/4388344/74978251-72fead80-53e9-11ea-8d93-237e96a6fa17.png)

**Comment by Mad-Spy** [comment]
It looks like Skullmaster has both local and linked versions of General?

![image](https://user-images.githubusercontent.com/29306451/74981227-c7298200-5429-11ea-8a60-55e542601643.png)

Is the Roster Editor just getting confused and displaying the wrong one, so it won't trigger the modifier?

**Comment by cartag** [comment]
I've removed the linked one, it should not have been there. I'm operating under a file that only has the independent one, not the link. It is set up the same as the Tzeentch one now.

**Comment by Mad-Spy** [comment]
It's working for me now, once I've removed the Linked "General" entry.

**Comment by Mad-Spy** [comment]
You have 2 Skullmasters. One in Chaos Data.cat and one in Khorne.cat. 

The Battalion links to the Khorne.cat version, and the Bloodcrusher switch links to the Chaos Data version.

If that's not deliberate, then that might be the problem?

**Comment by cartag** [comment]
Thank you for the second set of eyes. I'm embarrassed now. I've been bashing my head against this for entirely too long.
