### ISSUE TITLE
Error copying units from one data editor to another where categories are missing

### ISSUE THREAD

**Issue by cartag** [BattleScribe/Release#133]
When copying a unit from one data file to another, Unit A from Data File 1 (DF1) to Data File 2 (DF2), you get an unrecoverable error if the categories don't match in DF2. 

Steps to duplicate:
Create Unit Test1 in DF1. Add category Cat1 to DF1 and add to SSE of Test1. 
Copy Test1 from DF1 to DF2. Below error is shown:
![image](https://user-images.githubusercontent.com/4388344/74986262-751b3900-53f6-11ea-9951-2d8434a9e1bc.png)

Doubleclicking that link will not take you to anything that can be changed. A selection at the top between these two that is labeled as [Unknown Category] for any that are not matched would resolve.

**Comment by cartag** [comment]
![image](https://user-images.githubusercontent.com/4388344/74986900-3f2a8480-53f7-11ea-9da1-0090b111bb7a.png)

**Comment by Jonskichov** [comment]
Fixed in:
Desktop: 2.03.13.142
Android: 2.03.19.328
iOS: 2.03.11.147
