### ISSUE TITLE
RSEs in Libraries always load into a roster, even if "Import root entries" box is unchecked.

### ISSUE THREAD

**Issue by alphalas** [BattleScribe/Release#140]
Example: 40k repo, IG-lib branch. AM-Library is loaded into FW Elysians. The import root entries box is unchecked, and the specifically required SSEs are linked to RSEs in Elysian cat.
![Screen Shot 2020-02-22 at 12 06 14 AM](https://user-images.githubusercontent.com/15703066/75087156-cb799c00-550a-11ea-8a6b-66a7135cef10.png)
![Screen Shot 2020-02-22 at 12 05 29 AM](https://user-images.githubusercontent.com/15703066/75087157-ccaac900-550a-11ea-9799-829e202f7492.png)
![Screen Shot 2020-02-22 at 12 12 12 AM](https://user-images.githubusercontent.com/15703066/75087158-cd435f80-550a-11ea-9684-c417ec9f3169.png)

I'm assuming this behavior is unintended.

**Comment by Jonskichov** [comment]
I've just tried this (using the data in the 40k "AM lib bug" branch) on both mac and windows using v2.03.12, and I don't seem to be able to reproduce the issue...

**Comment by alphalas** [comment]
strange - it definitely was happening lol - I did circumvent the issue by removing the RSEs in the library anyway. so I guess fixed? lol

**Comment by Jonskichov** [comment]
Turned out there _was_ a problem, and it's fixed: https://github.com/BattleScribe/Release/issues/173
