### ISSUE TITLE
Scrollbar When Selecting Repositories

### ISSUE THREAD

**Issue by GenWilhelm** [BattleScribe/Release#144]
When a repository or release has a very long name, the checkboxes to select data repositories are hidden by default, requiring the user to scroll to the right in order to find them.

Example:

![image](https://user-images.githubusercontent.com/22036809/75826111-a7397d00-5d9e-11ea-9bcb-994b3f4aa37b.png)

**Comment by Jonskichov** [comment]
No longer an issue
