### ISSUE TITLE
Catalog Child Forces points for units that don't have points at the root SE count double for Validation when points limits are set in the GST

### ISSUE THREAD

**Issue by OftKilted** [BattleScribe/Release#15]
Note: This occurs and is repeatable on iOS and Android and a similar symptom exists on desktop (This issue existed in previous builds, and is not something that came from the current build.)

Problem:
Add multiple units to a Child force that do not have their points set at the 'root'. (e.g. a unit that can increment the number of models within the unit) When the points are not at root, but are on an SSE under root the points total displays correctly, but is counted 'Double' when GST limitations have been set.

Example:
Warhammer Age of Sigmar (v28)
Add a Order - Stormcast Eternals v17 parent force.
Create a Pitched Battle (2000) list
This list has an 'Allies' limit of 400 points, and a total points limit of 2000 points.
Add a Order- Seraphon v20 child (allies) force.
Navigate to the 'Allies Force' (you may need to change the force view to 'Nested')
Select 'Unit Type of Other'
Add a unit of Saurus Guard, The base cost is shown as 100 points.
Add a second unit of Saurus Guard. This will give you 200 points calculated. (This shows up correctly)
(Note that there is no validation flag.)
Add a third unit of Saurus Guard. This will pop a 'Validation' error and report that:
 'You have spent 200pts too much from Allies (maximum 400pts).'
This indicates that the 300 points of units is being counted as 600 points of units for validation.
This validation error is not expected, and I should be able to add 100 more points of Allies units before this occurs.

Remove all units. Your roster should be 0 points.

Select 'Behemoth'
Add one Dread Saurian (400pts)
Note that there is no validation flag.
Add a second Dread Saurian (400pts)
Validation error that you have spent 400 points more than you have available in Allies.
This validation error is expected. I have spent 800 points on allies, and only am supposed to spend 400 points.

Unit differences in the Catalog:
For Saurus Guard, the points are on the SSE, under the SE for the Unit
e.g.
```
Root
SSE for Main Unit (Saurus Guard) (cost 0) 
| - SSE - 5x Saurus Guard (100 points) (Min 1 selection in Parent)
```

For the Dread Saurian, the points are on the root SE. And there is no incrementing SSE, where the points are.
e.g.
```
Root
SSE for Main Unit (Dread Saurian) (cost 400) 
```
Example Roster:
https://files.gitter.im/BSData/warhammer-age-of-sigmar/RVBA/Bug1a.jpg

Example Validation Error:
https://files.gitter.im/BSData/warhammer-age-of-sigmar/ojfB/Bug1b.jpg

**Comment by Jonskichov** [comment]
Turning off "and all child selections" in the allied force's constraint will solve this.

I'm not sure this is a "bug" per se.

It's summing the points of the Saurus Guard selection (100pts - the cost of a selection includes it's child selections) and the points of the child selections (the "5 Saurus" selection is 100pts) as it should when this box is ticked.

Whether it makes sense to allow this constraint setup is another question :D It doesn't make much sense... But perhaps there are situations where it does?

**Comment by OftKilted** [comment]
@jonskichov Are we looking for this force constraint in the GST or the data catalog?

**Comment by Jonskichov** [comment]
Gst, Allied sub-ForceEntry. You probably don't want this box checked on any force constraint that is points based (probably not for count based either)

**Comment by OftKilted** [comment]
Confirmed fixed! Thanks! 🥇
