### ISSUE TITLE
Inherited constraints and modifiers behaving oddly in 2.03.13?

### ISSUE THREAD

**Issue by Mad-Spy** [BattleScribe/Release#150]
Example is from the 40k Chaos Space Marines catalogue in the "Terminator Weapons" SSEG.

Roster Editor in 2.03.12

![image](https://user-images.githubusercontent.com/29306451/77529937-740f7880-6e88-11ea-81c1-294da840d4ae.png)

Roster Editor in 2.03.13

![image](https://user-images.githubusercontent.com/29306451/77530419-36f7b600-6e89-11ea-8e6d-d9153d2aff20.png)

No change in Data Editor

![image](https://user-images.githubusercontent.com/29306451/77530349-16c7f700-6e89-11ea-9814-13222f3c6001.png)

**Comment by Jonskichov** [comment]
Fixed in:
Desktop: 2.03.14.143
Android: 2.03.20.329
iOS: 2.03.12.148
