### ISSUE TITLE
Can "And All Child Selections" "And All Child Forces" be default checked?

### ISSUE THREAD

**Issue by alphalas** [BattleScribe/Release#151]
![Screen Shot 2020-03-27 at 10 10 50 AM](https://user-images.githubusercontent.com/15703066/77764833-ac8f8d80-7013-11ea-911b-5649e3bd80d2.png)

**Comment by Jonskichov** [comment]
I'm afraid not. Having this checked by default would mean a big performance hit as conditions would be considering _many_ more selections when they are checked.
