### ISSUE TITLE
Unable to view markdown list type on iOS Battlescribe Version 2.01.18

### ISSUE THREAD

**Issue by OftKilted** [BattleScribe/Release#16]
Unable to create “Markdown List” in most recent version of Battlescribe Version 2.01.18
This is replicatable by other Battlescribe iOS users.

After selection of type Markdown list the following pop up error appeared.

![ba595a9d-8673-493f-8d7e-29e0d410bbdc](https://user-images.githubusercontent.com/17132967/41258192-4fee188c-6d9d-11e8-87cb-d4f119548a90.jpeg)

**Comment by Jonskichov** [comment]
Definitely a bug

**Comment by Jonskichov** [comment]
Fixed in 2.01.20 on iOS
