### ISSUE TITLE
Data Editor Bug: Field labels collapse too soon when changing pane width

### ISSUE THREAD

**Issue by Mad-Spy** [BattleScribe/Release#167]
When resizing the right pane in the Data Editor, some field labels collapse well before they need to, as per the screenshot below. 

The Publication and Reference field labels have collapsed, making them unreadable, but there is plenty of screen space to show them. 
The Default Selection label has not collapsed, which would be the preferred behaviour.

![image](https://user-images.githubusercontent.com/29306451/80195390-ab05b500-8613-11ea-9a4e-a11c970598b5.png)

**Comment by Jonskichov** [comment]
Fixed in 2.03.17
