### ISSUE TITLE
Feature Request: Make Tab work again to move between fields

### ISSUE THREAD

**Issue by Mad-Spy** [BattleScribe/Release#168]
Looks like text fields in the new framework support tabbing, so it's no longer possible to tab between fields; you just end up entering tabs into the text field.

Hopefully this behaviour can be changed?

**Comment by Mad-Spy** [comment]
Ok, looks like it's just moved to being CTRL-Tab instead. My muscle memory is wasted!

**Comment by Jonskichov** [comment]
Not intended behaviour, I'll take a look

**Comment by Jonskichov** [comment]
Working OK with me using TAB...

Is this happening everywhere or on certain panels?

What system are you on? Win/Mac/Linux (lol)

**Comment by Jonskichov** [comment]
Fixed in 2.03.18.157
