### ISSUE TITLE
Category Link Name Attribute

### ISSUE THREAD

**Issue by GenWilhelm** [BattleScribe/Release#17]
Category links currently default to `name="New CategoryLink"` - is possible to have name of a new category link be set to the name of the category it is linking to (in the same manner as entry and info links)?

This would be enormously helpful.

Cheers!

**Comment by Jonskichov** [comment]
Noted! Definitely should be properly named. Thanks!

**Comment by Jonskichov** [comment]
Tested in 2.01.14 and seems to work properly? When you set a Link's target, the Link's name is changed appropriately

**Comment by GenWilhelm** [comment]
This was specifically in reference to Categories.

Every time I add one, it has the name `New CategoryLink`.

**Comment by Jonskichov** [comment]
You're right, this happens when setting categories via checkboxes. I'll get it sorted.

**Comment by Jonskichov** [comment]
Fixed in 2.01.15.114

**Comment by GenWilhelm** [comment]
Thanks, Jon! Appreciate you taking the time for the little things 😄 .

**Comment by Jonskichov** [comment]
👍

It all adds up!
