### ISSUE TITLE
Libraries displaying RSEs despite being told not to!

### ISSUE THREAD

**Issue by WindstormSCR** [BattleScribe/Release#173]
Found during construction of the separated SM cats on the [i broke all the sm lists] branch.

Hopefully a simple fix.

**Comment by Jonskichov** [comment]
Items set to not import are still being imported

**Comment by Jonskichov** [comment]
I'm not sure this is an issue.

e.g:
- SM: Has Shared Captain in Terminator Armour
- SM: Has root Link to said Captain, import is checked
- Salamanders: Also has link to said Captain

So you get two Captains: One from the imported link in SM, one from Salamanders' own link..

This has been the case for multiple examples I've looked at, but that's not to say there's not an issue.

If you could provide a concrete example, that would be good

**Comment by Jonskichov** [comment]
OK scratch that, you're talking about the Catalogue Link. I'm on it.

**Comment by Jonskichov** [comment]
Fixed in 2.03.17
