### ISSUE TITLE
X in Parent Validation on Profiles are considering the Entry as the originator instead of the profile.

### ISSUE THREAD

**Issue by DrTobogganMD** [BattleScribe/Release#175]
When adding a modifier and conditional to a Profile attached to a Shared Entry, the conditional treats the Shared Entry as the originator instead of the profile.  As we discussed, this seems to be intended but just to be sure - here are some details:

To replicate: Create a standard roster using Blood Bowl GST and the Simyin Cat. Add 2 Bonobo's to a list and give one 2 "MVPs Awarded" so that it's total SPP is 10. Click the "Toggle to Refresh Name and Allow Rolls" to refresh the entry name (Another issue entirely but I think that's been brought up already?)

You should see both bonobos entry names change.

Now do the same with a Chimpanzee to see what I would have expected to happen.
[Simyin - BB16.zip](https://github.com/BattleScribe/Release/files/4569268/Simyin.-.BB16.zip)

If I attempt to modify the profile name as long as At Least 1 X is in Parent and Child Selections - my assumption is that it should modify the title if shared entry it is attached to has 1 X. The current behavior treats the conditional as one level higher. So because the Shared Entry in question is a top level entry, it validates and applies the change to every entry in the roster.

Examples of "Parent" not working correctly.
![image](https://user-images.githubusercontent.com/16939161/80893819-57423e00-8c9b-11ea-976d-10782479fc3a.png)
![image](https://user-images.githubusercontent.com/16939161/80893822-5f01e280-8c9b-11ea-987a-052168a6a413.png)

This does not happen if I use "At Least 1 X in <GUID> and Child Selections". This works perfectly fine but makes copy/paste cumbersome as copying to a new catalogue obviously cannot parse the GUID, but it could easily take Parent.

Examples of the direct GUID reference working.

![image](https://user-images.githubusercontent.com/16939161/80893794-26fa9f80-8c9b-11ea-8fd4-417a5be12fbd.png)
![image](https://user-images.githubusercontent.com/16939161/80893803-40035080-8c9b-11ea-969d-45bfe02d943f.png)

**Comment by Jonskichov** [comment]
As we discussed in Discord, I think this is working as expected. Bear in mind the "parent" really means "parent entry" - or maybe more accurately "parent selection"

For example, if you have an Entry with a Profile on, and you put a Modifier on that Profile, the "Parent" is not said Entry - it is the parent of _that_ Entry.

**Comment by DrTobogganMD** [comment]
Yep that makes sense to me. I assumed the profile itself was considered an "Entry" but it makes sense that the associated entry is actually the root of the modifier.  I'll close this as there's no real issue :)
