### ISSUE TITLE
Data Editor Feature Release

### ISSUE THREAD

**Issue by Jonskichov** [BattleScribe/Release#177]
Planned features for upcoming Data Editor feature release

- Multiple data sources: https://github.com/BattleScribe/Release/issues/155
- "Archived" flag on repositories: https://github.com/BattleScribe/Release/issues/154

- Do not delete data before updating unless the source is available: https://github.com/BattleScribe/Release/issues/145

- Error messages in Data Editor: https://github.com/BattleScribe/Release/issues/176
- Search functionality in Data Editor: https://github.com/BattleScribe/Release/issues/158
- Catalogue Game System Version field should be updated when saving: https://github.com/BattleScribe/Release/issues/156
- Allow users to collapse imported items in Data Editor: https://github.com/BattleScribe/Release/issues/182

**Comment by amis92** [comment]
You mean it's all done?
