### ISSUE TITLE
Modifiers to Force Entries in GST are saved, but hidden in the editor upon re-opening GST for editing

### ISSUE THREAD

**Issue by OftKilted** [BattleScribe/Release#18]
Issue:
When configuring a GST to have Force Entries that can be modified based on a condition, those modifications save to the GST, but are not showed by the editor when re-opening the GST for any additional editing. (they don't appear to actually be purged ... just unable to be shown by in the Data Editor ... and they seem to work okay in the Roster Editor.)

You can see the issue in ~~https://github.com/BSData/warhammer-age-of-sigmar/tree/GST-Testing~~
https://github.com/BSData/warhammer-age-of-sigmar/tree/AoS-V2.0-Points-Update-InProgress

If you open a new roster and select *PITCHED BATTLE* (not any of the items with the numbers after them) you get variables that change the name and restrictions. If you open the GST, all of the modifiers are no longer showing in the editor ... (even though they appear to work okay in the roster editor)

**Comment by Jonskichov** [comment]
Been deep into porting 2.02 to iOS, sorry I missed this!

I'll take a look. Thanks!

**Comment by OftKilted** [comment]
This appears to be similar to https://github.com/BattleScribe/Desktop-Alphas/issues/168

**Comment by DrTobogganMD** [comment]
This appears to happen to non GST entries as well - so really any force entry in a cat or gst file.

**Comment by OftKilted** [comment]
Most recent production stable release adds in the ability to see the force modifiers.

**Comment by Jonskichov** [comment]
Fixed in 2.01.15.114
