### ISSUE TITLE
Loss of Visual Hierarchy in new visual update 

### ISSUE THREAD

**Issue by TomWija** [BattleScribe/Release#187]
Wrote a small write-up of my thoughts on the official subreddit here: https://www.reddit.com/r/BattleScribe/comments/gf480w/small_ui_fix_for_huge_readability_improvements/

Basically, while I love the modern feel of this new update it's come with a few design "bugs" most importantly being the loss of visual hierarchy.

A lot of this comes down to the fact that the changes have added a lot more spacing, removing a lot of the hierarchy previously gained through the use of indentation in the old design.

This
![image](https://user-images.githubusercontent.com/7304281/81392974-6996fe80-9117-11ea-9006-32f97050256a.png)

Is significantly easier to read and parse than this:
![image](https://user-images.githubusercontent.com/7304281/81392935-5a17b580-9117-11ea-8afe-5587b56c3913.png)

And one of the biggest issues with this new layout is it's incredibly hard to tell Forces apart. Look at how similar the new Blood Angels Battalion Detachment looks to just an HQ slot. It all blends in.

Here is a suggestion for a straightforward way to improve visual hierachy:
![image](https://user-images.githubusercontent.com/7304281/81393159-c4305a80-9117-11ea-834d-359d0cbeda44.png)

* Have the Forces be a a darker blue
* Use a very slightly darker white-blue to separate the units

With these two changes alone we see a massive improvement to readability and after adding these we have the following changes to our visual hierachy:

* Selected Item: Stays the same with highlighted orange
* Top Level Item (Battalions etc.): Light Blue => Dark Blue
* Mid level item (HQs, Troops etc.): Stays Light Blue
* Bottom Level Item (Specific Units, e.g. Primaris Intercessors): White => White/Grey alternating

**Comment by Jonskichov** [comment]
(Mostly) Fixed in:
- Desktop 2.03.21.164

I'll continue to tweak the UI going forward.

Thanks for the feedback :)
