### ISSUE TITLE
UI Elements like buttons not immediately obvious

### ISSUE THREAD

**Issue by TomWija** [BattleScribe/Release#188]
This is another UI related bug report that I didn't want to lump in with the other [issue](https://github.com/BattleScribe/Release/issues/187) as it relates to separate concerns.

A thing we've lost in this visual update is the ability to quickly scan the UI with our eyes and understand what things do:

* The icons on the menu bar no longer explain what they do without hovering over them
![image](https://user-images.githubusercontent.com/7304281/81393473-56d0f980-9118-11ea-919e-f240c0710b58.png)
Vs the old, far more readable style:
![image](https://user-images.githubusercontent.com/7304281/81393507-64867f00-9118-11ea-8b2d-aa4b7b5ab1bf.png)

* It's not obvious where you go to add more forces to the roster, I had no idea you had to click this:
![image](https://user-images.githubusercontent.com/7304281/81393561-7c5e0300-9118-11ea-90ca-90cf7b9b33a9.png)
compared to the immediately obvious button in the old design
![image](https://user-images.githubusercontent.com/7304281/81393608-8ed83c80-9118-11ea-8c6b-f88a2ff1e568.png)

* The plus and minus icons seem like the wrong Icons to use for expanding and folding catalogues. I immediately thought they were used to add new units or forces to a list. 
![image](https://user-images.githubusercontent.com/7304281/81393716-bb8c5400-9118-11ea-93de-30d22c98e079.png)

**Comment by Jonskichov** [comment]
(Mostly) Fixed in:
- Desktop 2.03.21.164

I'll continue to tweak the UI going forward.

Thanks for the feedback :)
