### ISSUE TITLE
Conditions with link child not working

### ISSUE THREAD

**Issue by Jonskichov** [BattleScribe/Release#192]
Thousand sons cat

**Comment by Mad-Spy** [comment]
![image](https://user-images.githubusercontent.com/29306451/81866168-b8ed8c80-9566-11ea-81b7-d058b4ca3430.png)

![image](https://user-images.githubusercontent.com/29306451/81866237-d1f63d80-9566-11ea-8b59-319de21533bc.png)

The two Missile Launcher entries should be mutually exclusive and hide if the other one is selected. The modifier should trigger on the specific entry in each group (the target is the specific instance) and only hide that specific instance.

However, the trigger is hiding _both_ instances of the launcher when one is selected.

![image](https://user-images.githubusercontent.com/29306451/81866751-914af400-9567-11ea-9843-b6a81f8087de.png)

**Comment by Jonskichov** [comment]
Uncheck "shared" on the conditions :)
