### ISSUE TITLE
Catalogue name is somehow linked to author name

### ISSUE THREAD

**Issue by L3610N115** [BattleScribe/Release#197]
All my catalogues had my name in the Author Name window.
I just noticed that this has changed and the author of the catalogue is now the name of the catalogue.
![grafik](https://user-images.githubusercontent.com/47950292/82119325-c761c100-977d-11ea-87dd-608e6b4a01b1.png)

If I change the author name in any way, the file name changes too.
![grafik](https://user-images.githubusercontent.com/47950292/82119337-e3656280-977d-11ea-95d8-2e2189627a11.png)

**Comment by Jonskichov** [comment]
Fixed in 2.03.20.161
