### ISSUE TITLE
UI/Validation not updating based on categories added via entries.

### ISSUE THREAD

**Issue by DrTobogganMD** [BattleScribe/Release#198]
If I have a shared entry that is hidden unless ancestor is instance of X, that shared entry will not immediately show if X category is added via another method until a 3rd unrelated entry is toggled. 

This seems to be a validation issue and not a UI issue. Meaning, the category is not actually added when it should be.  

Shared Entry that is hidden:
![image](https://user-images.githubusercontent.com/16939161/82125847-5bc42780-976e-11ea-832a-0908b59993a7.png)

"Dummy Entry":
![image](https://user-images.githubusercontent.com/16939161/82125873-8615e500-976e-11ea-848c-d136060682f4.png)

Category Modifiers:
![image](https://user-images.githubusercontent.com/16939161/82126000-371c7f80-976f-11ea-928f-c3b26548c0ff.png)

Attached is a video showing the behavior.  Please reach out on discord - it's gonna be much easier to explain over there.

[Roster Editor 2.03.20 - New Roster (Blood Bowl 2016 v27) 2020-05-16 12-15-31.zip](https://github.com/BattleScribe/Release/files/4638813/Roster.Editor.2.03.20.-.New.Roster.Blood.Bowl.2016.v27.2020-05-16.12-15-31.zip)

**Comment by Jonskichov** [comment]
start an amazon team - add any player. eagle warrior thrower for example
Give 1 MVP and 1 Misc SPP to total 6SPP
Data logic should change the name of the player and show "Star Player Rolls" shared entry group
It does not.
Now check the toggle to refresh name/rolls and it will appear.

**Comment by Jonskichov** [comment]
Done in:
- Desktop: 2.03.21.165
- Android: 2.03.25.337
- iOS: 2.03.15.151 (pending approval)
