### ISSUE TITLE
(v2.03.20.162) Only Rule info links possible in Shared Info Groups

### ISSUE THREAD

**Issue by Mad-Spy** [BattleScribe/Release#199]
When adding an Info Link to a shared Info Group, it's not possible to select the "Profile" type; only Rule is available.

![image](https://user-images.githubusercontent.com/29306451/82195503-4a0a8d80-98f0-11ea-951f-56b77907b15d.png)

Copying and pasting a Profile Info Link works.

**Comment by Jonskichov** [comment]
Fixed in:
- Desktop 2.03.21.164
