### ISSUE TITLE
xplat-inconsistent order of categories on Flatten

### ISSUE THREAD

**Issue by amis92** [BattleScribe/Release#2]
It seems that there are differences in how categories are ordered between platforms:

https://github.com/BSData/wh40k/issues/2003

Also the order is not in any way specified logically (nonalphanumerical, possibly by ids?); developers would probably want to keep the order as-is in gst/cat; same as when Flatten is not on.

**Comment by Jonskichov** [comment]
Fixed in 2.01.09
