### ISSUE TITLE
(v2.03.20.162) UI Scroll Bar on roster view cuts off right side

### ISSUE THREAD

**Issue by DrTobogganMD** [BattleScribe/Release#201]
Title.

![image](https://user-images.githubusercontent.com/16939161/82743757-58fca000-9d35-11ea-8493-8a3b76e30d6b.png)

It eventually fades, but the fade time is slow enough that it's an issue when viewing the roster.

**Comment by Jonskichov** [comment]
Fixed in:
- Desktop 2.03.21.164
