### ISSUE TITLE
Primary Category Modification Does Not Update UI on Mobile/Android

### ISSUE THREAD

**Issue by DrTobogganMD** [BattleScribe/Release#202]
In the latest blood bowl upgrade branch: https://github.com/BSData/bloodbowl/tree/BBUpgrades I've added logic to re-assign the primary category of a player that is either Missing Next Game or Dead. Indicated by associated Shared Entries.  In testing the data on android (app version 2.03.23), we find that these entries cause the player to disappear from the UI (Meaning the "Player" category is removed as expected) but it does not show up in a Dead/MNG (Miss next game) Category. When viewing the roster, the player shows up correctly as Dead/MNG, meaning the new primary category is indeed set, but the UI itself did not update.

To replicate (currently android only, I have not been able to test on IOS and cannot replicate on desktop):

Add an Amazon Team. Add 2 Eagle Warrior Throwers and a Koka Kalim Blitzer. Check the Injury box on both Koka Kalim Blitzer and one Eagle Warrior Thrower.  In the injury entry for the Eagle Warrior Thrower, check the "DEAD" box. In the injury entry for the Blitzer, check the Miss Next Game box. 

The expected result is each should be removed from the Players section of the UI and added to a newly shown Dead Players / Missing Next Game.

The result shown is that both players disappear entirely. Now view the roster output and you should see both players in the correct Dead/MNG categories.

![Screenshot_20200603-104952](https://user-images.githubusercontent.com/16939161/83671246-fcea1500-a599-11ea-8afc-deb59d9b880f.jpg)
This is the view after the injuries are checked.

![Screenshot_20200603-105000](https://user-images.githubusercontent.com/16939161/83671261-04112300-a59a-11ea-941b-9ae9de4db2df.jpg)
This is the roster view after injuries are checked, note the players in the dead/mng section.

![Screenshot_20200603-105030](https://user-images.githubusercontent.com/16939161/83671287-0ffce500-a59a-11ea-97bb-8d30b76b6940.jpg)
This is the errors page. Note it believes the roster has 2 of 11 "Players", indicating the 2 injured ones have had the Player category removed as expected.

**Comment by Jonskichov** [comment]
Fixed in:
- Android 2.03.03.25.336

iOS pending.

**Comment by Jonskichov** [comment]
Done in:
- Desktop: 2.03.21.165
- Android: 2.03.25.337
- iOS: 2.03.15.151 (pending approval)
