### ISSUE TITLE
Data Editor - Stable Release - Missing “Saved” and “Incremented” notifiers next to upper exit right button

### ISSUE THREAD

**Issue by OftKilted** [BattleScribe/Release#21]
The most recent public stable release has lost the “unsaved/saved” red notification text, and the “incremented/not incremented version” text next to the exit button in the upper right of the UX for Data Editing, this has been identified specifically on the Mac client, and may exist on Windows as well.

**Comment by FarseerVeraenthis** [comment]
This exists on Windows too - I checked last night after downloading the newest version and it is the same as noted by @OftKilted

**Comment by Jonskichov** [comment]
Unfortunately I noticed this issue as I was closing the last batch, otherwise it would have been included!

This will be a problem with all desktop versions. I'll get it sorted, but since it's not a deal breaker and I'm back in to sorting out 2.02 for iOS it's going to need to wait for a bit :)

**Comment by Jonskichov** [comment]
Fixed in version 2.01.16
