### ISSUE TITLE
Editor request: Add list of entry categories

### ISSUE THREAD

**Issue by amis92** [BattleScribe/Release#22]
When editing files, it's very burdensome and inconvenient to check which Categories are linked/selected for a given entry. Right now, the editor view is:

![image](https://user-images.githubusercontent.com/2671396/43063846-710b0eea-8e5d-11e8-8246-157541328d5b.png)

I'd propose to add a non-editable list of selected categories just above the selection list, as a simple text area. It could be as simple as comma-separated names list.

Primary category should be also marked somehow, either in a separate line above others, or by just a bold font.

**Comment by CrusherJoe** [comment]
I like the concept (the Categories list is out of control and you have to scroll for what feels like miles to get what you want to check) but I have some consistency concerns. Where will this list come from? Is there way we could pre-define Categories (KEYWORDS!) for a catalog once and then only make additions on a per-entry basis?

**Comment by OftKilted** [comment]
As a list of currently selected categories, it would add benefit to the data editor.

The list should display the selections in the order in which they will show up in the “category list” on the unit.

**Comment by Mad-Spy** [comment]
If possible, it would be good to have some kind of ordering functionality. 

The current functionality adds them to the display in the same order they are added to the unit, which means any errors may mean removing and re-entering multiple entries.

**Comment by Jonskichov** [comment]
Added in version 2.01.16 (except the primary category highlight - just noticed that! Next version)
