### ISSUE TITLE
Selections of Root Entries hidden by modifier don't give error

### ISSUE THREAD

**Issue by amis92** [BattleScribe/Release#23]
BattleScribe Roster Editor (Desktop v2.01.15.114)

Repro:
1. Install: https://ci.appveyor.com/api/buildjobs/kmyqu8v9cd39nyxa/artifacts/artifacts%2Fsnapshot.bsr
2. Create roster, add `Tyranids` force.
3. Add `Non-specialist` `Tyranid Warrior`
4. Change `List Configuration` to `Campaign: Command Roster`

Observe no error, and Tyranid Warrior entry in Available Entries stays. Expected error "too many of Tyranid Warrior in Non-Specialist (hidden)".

If you remove the Warrior selection from roster, the entry from Available Entries gets hidden, which implies that the above is not the desired behavior.

![image](https://user-images.githubusercontent.com/2671396/43312165-c51c462a-918c-11e8-9de6-f702162d1196.png)

**Comment by Jonskichov** [comment]
Fixed in version:

- 2.01.16 on desktop
- 2.01.23 on Android
- 2.01.20 on iOS
