### ISSUE TITLE
Hiding through `Not Instance Of` condition causes constraints to be ignored

### ISSUE THREAD

**Issue by amis92** [BattleScribe/Release#24]
Triggered by: https://github.com/BSData/wh40k-killteam/issues/67

Copied relevant issue text:

> There's currently a bug in BattleScribe that causes constraints to not be validated on selections with a conditional modifier that sets hidden using the `Not Instance Of` condition type.

v2.01.15

**Comment by Jonskichov** [comment]
Unable to reproduce right now using Killteam version 1.0.2 (https://github.com/BSData/wh40k-killteam/tree/v1.0.2) and older versions of BattleScribe back to 2.01.14. Is this still an issue?

Can you provide some info on what I should/should not be seeing and how to reproduce?

I added a flayed one: 
1) As a specialist, Specialist Types are visible, but not visible if they're not a specialist
2) The Comms Specialist Type is not visible for the flayed one, but is visible for others

(I'll refer this in Dr Toboggan's issues on the BSData page)

**Comment by Jonskichov** [comment]
Fixed in version:

- 2.01.16 on desktop
- 2.01.23 on Android
- 2.01.20 on iOS
