### ISSUE TITLE
Minimum Percentage Selections in Parent

### ISSUE THREAD

**Issue by GenWilhelm** [BattleScribe/Release#29]
Entries that behave collectively (i.e. ones with no non-collective children) treat the `Minimum X% Selections in Parent` constraint as both a percentage and an absolute.

For example, we have such an entry with `Minimum 50% Selections in Parent`. As soon as this entry is incremented in the roster, it will increase the number of selections to 50 and will not allow it to be reduced below 50.

This bug exists on desktop, but I was unable to reproduce it on android.

**Comment by Jonskichov** [comment]
Fixed in version 2.01.16
