### ISSUE TITLE
JRE 9 Required when running EXE on windows.

### ISSUE THREAD

**Issue by DrTobogganMD** [BattleScribe/Release#33]
![image](https://user-images.githubusercontent.com/16939161/54278788-6038f300-4561-11e9-84c0-d8f0c8720edd.png)

This does not happen when running the JAR, just the EXE.  Latest Java available from Oracle is 8.201 - which I have installed.

As far as I can tell. Java 9 currently only exists as a JDK build.

**Comment by morvael** [comment]
There will be no JRE for Java 9+ (current is Java 11). Oracle is doing everything it can to push Java out from desktops (I guess they want it to be used only on servers).

edit: anyway, this looks like something in the launcher that generates the exe and probably can be easily fixed.

**Comment by DrTobogganMD** [comment]
Huh, good to know!  Not the biggest issue since you can run the jar file but still annoying.

**Comment by morvael** [comment]
I think future lies in http://openjdk.java.net/jeps/343 and java modules - generating native installers that will contain only that part of full JDK that a given app requires, bundled together. The range of desktop solutions grows thin otherwise - applets gone, WebStart gone, JRE gone, no official installers for OpenJDK...

**Comment by Jonskichov** [comment]
Hm, interesting. The new version now uses an embedded JRE 9 (I'll switch it to JRE 11 soon, long story...).

I've just double checked on my machine and running the exes does launch the app and I've confirmed it's using the embedded JRE executable (not the JDK 9 I have installed, i.e. the way things used to work)

It _is_ a 64bit JRE 9 included with the app. Could this be the problem?

**Comment by morvael** [comment]
Page says "BattleScribe for Mac or PC requires Java 8 or above."
You may wish to update that information.

**Comment by Jonskichov** [comment]
I also need to remove the Google+ links ;)

But yeah I'm on it.

FWIW, the app is still compiled for Java 8, so running the jars with a JRE 8 installation will be fine.

The embedded JRE just makes it easier for users and also Java 9 and up handles high DPI screens properly.

**Comment by morvael** [comment]
No doubt the code must remain Java 7/8 if you want easy sharing with Android version.

**Comment by DrTobogganMD** [comment]
This is the universal zip as well, not the installer - that I was using.

**Comment by morvael** [comment]
So it comes with the .exe but not the bundled JRE? I guess the .exe will have to go then from the universal zip.

**Comment by DrTobogganMD** [comment]
Right, just installed over my normal unzip path - it now has the JRE folder and runs fine via EXE. Should just need to add the JRE folder to the universal zip I think?

**Comment by Jonskichov** [comment]
Ahhhh ok that makes sense. The exe launchers are configured to search for JRE 9+ now, yes. I forgot that they're bundled in with the zip version!

Copying the JRE folder will work just fine.

I can't really include a JRE with the zip version as it's supposed to be universal. I'll need to figure out what to do here.

**Comment by morvael** [comment]
Exactly, JRE is platform dependent so it can't be part of universal ZIP.

**Comment by DrTobogganMD** [comment]
Add all of them? MacOS, Linux, and PC?

**Comment by Jonskichov** [comment]
Then the download would be massive...

I can probably change the exe launchers to revert to a JRE 8 installation if an embedded JRE can't be found.

**Comment by Jonskichov** [comment]
I've rebuilt the exes to only require Java 8. It'll use the embedded JRE 9 if it's there, otherwise will use the system's JRE 8+ as it used to.

I've uploaded the new build so it should be available now (no version number changes)
