### ISSUE TITLE
Hidden items with min 1 constraint give validation error

### ISSUE THREAD

**Issue by Mad-Spy** [BattleScribe/Release#36]
e.g. I have an Shared Selection Entry group with a hidden modifier and a min1 constraint as per the screenshot below. If I link that into a Shared Selection Entry, the min1 constraint is incorrectly validated even if the SSEG is hidden.

![image](https://user-images.githubusercontent.com/29306451/54369041-1d644180-466d-11e9-8888-3e21b2deb4c2.png)

This example is from Adeptus Astartes.cat in the https://github.com/BSData/wh40k-killteam/

**Comment by Jonskichov** [comment]
Can you confirm this is the case in version 2.01.16?

**Comment by Mad-Spy** [comment]
Yes, this is a new issue introduced in 2.01.16 on Windows.

**Comment by Jonskichov** [comment]
Fixed in 2.01.17 on desktop

**Comment by Jonskichov** [comment]
Fixed in 2.01.24 on Android

**Comment by Jonskichov** [comment]
Fixed in 2.01.20 on iOS

**Comment by DrTobogganMD** [comment]
@Jonskichov is there a chance this introduced another bug?

After updating, the following conditional is always returning true:

![image](https://user-images.githubusercontent.com/16939161/54888688-45258780-4e6d-11e9-84f6-4e7d24173fa3.png)


So even in a "Super-Heavy Detachemtn +3CP" the profile hides when it shouldn't.

**Comment by Jonskichov** [comment]
Certainly could be...

Can you let me know the specifics of how to reproduce (catalogue, expected vs actual results etc) and I'll take a look.

Thanks!

**Comment by DrTobogganMD** [comment]
Main 40k repo: https://github.com/BSData/wh40k
Imperium - Questor Imperialis catalog

Create a new roster with a Super-Heavy Detachment +3CP

Select any household in the household choice (I'm using Household: Cadmus as an easy test):
![image](https://user-images.githubusercontent.com/16939161/54888782-3d1a1780-4e6e-11e9-86d1-ad50ab3fd461.png)

It should show the following in roster view: 
![image](https://user-images.githubusercontent.com/16939161/54888794-4d31f700-4e6e-11e9-8da6-b4e6b50e87c1.png)

However it shows instead: 
![image](https://user-images.githubusercontent.com/16939161/54888803-5e7b0380-4e6e-11e9-8967-04d59b2aa7c8.png)

Removing the hide conditional on the profile link fixes the issue but the hide conditional should not be returning true in this case, as the ancestor is indeed an instance of Super-Heavy Detachment +3CP

**Comment by DrTobogganMD** [comment]
[IK Test.zip](https://github.com/BattleScribe/Release/files/3001100/IK.Test.zip)

Here's a copy of the GST, Cat, and test roster file.

**Comment by Jonskichov** [comment]
Found the problem. The fix will be in the next release(s) 👍

**Comment by Jonskichov** [comment]
Fixed in 2.02.00.120.BETA
