### ISSUE TITLE
Bug when creating roster (Android)

### ISSUE THREAD

**Issue by amis92** [BattleScribe/Release#42]
This is an issue that existed on 2.01 as well and continues in 2.02; Android flavor. iOS may suffer the same issue.

**Repro steps:**
1. Click '+' to create new roster on main screen
2. Select any catalogue and any force type for it.
3. On the screen of `Edit Forces` click '+' to add a second Force.
4. Either:
    a. Click 'back' arrow (either system one or the app one)
    b. Select any parent force and do a)

**Outcome:** app asks whether roster creation should be cancelled.

**Expected outcome:** App returns to `Edit Forces` screen (for a.) or selection of parent force (for b.).

**Comment by Jonskichov** [comment]
Ah yes, you're right. I'm sure I stumbled on this myself then promptly forgot about it :D

**Comment by Jonskichov** [comment]
Fixed in:
Android: 2.02.02 
iOS: 2.02.03

Note that as of writing the iOS version is currently being reviewed by Apple. It should become available for download within 24hrs (roughly).
