### ISSUE TITLE
2.02: validation regression bug

### ISSUE THREAD

**Issue by amis92** [BattleScribe/Release#43]
**Repro steps:**
1. Use wh40k data: https://github.com/BSData/wh40k/releases/tag/v1.3.0
2. Use Desktop v2.02.01.122 or Android v2.02.01.297 BattleScribe
3. Create new roster with one T'au Empire/Patrol Detachment force
4. Add Elites/XV25 Stealth unit
5. Observe 2 validation errors (expected: no HQ and no Troops)
6. Add 1x `Stealth Shas'ui w/ Fusion blaster`
7. Observe new validation error (max 0 Fusion Blasters)

**Expected outcome:** no new validation error occurs.

This works under 2.01.15 and https://github.com/BSData/wh40k/releases/tag/v1.2.29

Except being converted to 2.02, the Tau file did not change.

**Comment by Jonskichov** [comment]
Might be a merge issue from working some of the 2.01 bugs. I'll look into it, thanks 👍

**Comment by amis92** [comment]
If you uncheck the Shared box on Repeat of the Fusion Blaster modifier, this works.

**Comment by Jonskichov** [comment]
https://github.com/BSData/wh40k-7th-edition/issues/2880

**Comment by Jonskichov** [comment]
Fixed in:
Desktop: 2.02.03
Android: 2.02.02 
iOS: 2.02.03

Note that as of writing the iOS version is currently being reviewed by Apple. It should become available for download within 24hrs (roughly).
