### ISSUE TITLE
Rules/profiles not rendering when viewing

### ISSUE THREAD

**Issue by Jonskichov** [BattleScribe/Release#47]
https://battlescribe.uservoice.com/admin/v3/suggestions/37469686/

**Comment by Jonskichov** [comment]
https://www.reddit.com/r/BattleScribe/comments/bgx19a/rules_not_showing_at_the_bottom_of_lists_anymore/

**Comment by TimCoraxAudio** [comment]
I too am experiencing this problem in the Gates of Antares data files. Seemed to happen ever since the latest update

**Comment by morvael** [comment]
I think this happens in all the files, as it's an issue of the application itself, not the data.

**Comment by ghost** [comment]
+1

**Comment by Xemit64** [comment]
Saw this on Adeptus Titanicus when I was adding Errata to rules. Discovered that if I remove the publication reference from the one new rule I edited, that the summary returned. So if just one rule has a reference set, the summary no longer is shown. In this rule set, none of the other rules have references except the Legios. If user adds a Legio and then sets it to anything the summary disappears again. Checking the data and the selection adds rules and all of them have references set. Remove the reference and summary comes back.

So bug in BattleScribe if any visible summary rules have a reference set, the summary is not shown.

**Comment by morvael** [comment]
Don't want to remove references, they are all my rules have (as per agreement with game publisher I provide only reference to rules - book and page number).

**Comment by Jonskichov** [comment]
Fixed in:
Desktop: 2.02.03
Android: 2.02.02 
iOS: 2.02.03

Note that as of writing the iOS version is currently being reviewed by Apple. It should become available for download within 24hrs (roughly).
