### ISSUE TITLE
Ctrl C, V, X blocked by stolen focus

### ISSUE THREAD

**Issue by morvael** [BattleScribe/Release#5]
Upon selecting an item in Data Edtior's tree focus is placed on Basics Name field. This prevents Ctrl C, V, X shortcuts from working. To work around this one has to make a second click to restore focus to tree node.

**Comment by morvael** [comment]
If the second click on tree node is too fast this triggers expansion/collapse of tree node, which isn't helping.

**Comment by Jonskichov** [comment]
The name field no longer takes focus as of 2.01.10
