### ISSUE TITLE
Entry Links to "not local" entities not allowing constraints or modifiers

### ISSUE THREAD

**Issue by Mad-Spy** [BattleScribe/Release#52]
After adding an entry link or info link pointing to a "not local" entity (whether from a GST or Library catalogue), it is no longer possible to add any constraints or modifiers via the right-click menu. This was possible in 2.01. Adding them to a local shared entity works fine.

Adding a constraints/modifiers via the "Quick Constraints" options or by copying and pasting from another entry is still possible.

![image](https://user-images.githubusercontent.com/29306451/57036149-60916880-6c4b-11e9-8024-fa387f807265.png)

**Comment by Jonskichov** [comment]
Fixed in:
Desktop: 2.02.03
