### ISSUE TITLE
Unable to add more than 1 Catalogue Link - Data Editor 2.02.01

### ISSUE THREAD

**Issue by cartag** [BattleScribe/Release#55]
Unable to add more than one catalog, get screen below when trying. Right side freezes up, no error at bottom, cannot change anything until deleting the empty catalog link.

![image](https://user-images.githubusercontent.com/4388344/57049240-69c30b00-6c34-11e9-8ee8-a62b533a7e93.png)

**Comment by Jonskichov** [comment]
Fixed in:
Desktop: 2.02.03
