### ISSUE TITLE
Data Editor - Ancestor Not Instance Of Issues from Library to .CAT

### ISSUE THREAD

**Issue by cartag** [BattleScribe/Release#56]
Rough setup: Data library has SSEG, set to Adjust Min in Force if Ancestor is not instance of "Named" category. 

![image](https://user-images.githubusercontent.com/4388344/57049363-05ed1200-6c35-11e9-9b37-1cbf51cbea94.png)

Other data file has nested groups, and at the SSE level, the units that have a name and are unable to take a Command Trait are set with a Category of Named. This isn't triggering for adjusting min/max, but a Show/Hide modifier WILL work nested this far. 

Named SSE
![image](https://user-images.githubusercontent.com/4388344/57049485-814ec380-6c35-11e9-808c-c7f0a9d138b8.png)

General SSE
![image](https://user-images.githubusercontent.com/4388344/57049496-89a6fe80-6c35-11e9-81df-f38c723bdbfa.png)

Command Trait SSEG
![image](https://user-images.githubusercontent.com/4388344/57049516-975c8400-6c35-11e9-8045-1148f39926e9.png)

**Comment by Jonskichov** [comment]
@cartag Is this still a problem in 2.02.03?

**Comment by Jonskichov** [comment]
I'll assume everything is OK :)
