### ISSUE TITLE
Primary Catalogue Not Instance Is Always False

### ISSUE THREAD

**Issue by GenWilhelm** [BattleScribe/Release#57]
Using the condition `Not Instance Of` with the query `Primary Catalogue` always returns false, regardless of which catalogue is in use.

**Comment by Jonskichov** [comment]
Fixed in:
Desktop: 2.02.03
Android: 2.02.02 
iOS: 2.02.03

Note that as of writing the iOS version is currently being reviewed by Apple. It should become available for download within 24hrs (roughly).
