### ISSUE TITLE
Validation problems with Detachments

### ISSUE THREAD

**Issue by Dunamis55** [BattleScribe/Release#58]
Issues exist with validation of detachments, causing an error to be thrown and detachment rule validation to be corrupted during that session.
Confirmed to be occurring with Battlescribe v2.02.03 on Windows desktop.

Example (note that the different detachment requirements have 'leaked' into each other):
![image](https://user-images.githubusercontent.com/36267768/57521127-550f0300-7317-11e9-8534-991da95bae5c.png)

Steps to replicate issue:

1. Create a New Roster and add a single detachment of any type.
2. Press Ok to begin editing the roster.
3. Click the Edit Forces button and then add 3 new detachments of differing types so that all 4 detachments are unique detachment types (e.g. 1 Vanguard, 1 Unbound, 1 Super Heavy & 1 Supreme Command).
4. Press Ok.
5. Everything should now be broken in the requirements.

Error text generated the moment a 4th unique detachment is added:
![image](https://user-images.githubusercontent.com/36267768/57521107-49bbd780-7317-11e9-8eda-2662c8ab2a55.png)

**Comment by Dunamis55** [comment]
Originally reported via [BSData issue 4957](https://github.com/BSData/wh40k/issues/4957).

**Comment by Jonskichov** [comment]
Fixed in:
Desktop: 2.02.04
Android: 2.02.03
iOS: 2.02.04

Note that as of writing the iOS version is currently being reviewed by Apple. It should become available for download within 24hrs (roughly).
