### ISSUE TITLE
Delayed Validation On Conditional Hidden

### ISSUE THREAD

**Issue by GenWilhelm** [BattleScribe/Release#6]
Selected entries do not immediately give a warning when they become hidden due to a conditional modifier.

In the following example, a commander may only select the "Relic of Lost Cadia" if the force it is in has selected "Cadian" as its "Regimental Doctrine". Selecting the Relic and then changing the Doctrine makes an invalid list, but a warning is not displayed until the commander is updated (either by changing another selection within the commander entry, or by reloading the roster).

Valid selection:
![valid](https://user-images.githubusercontent.com/22036809/38093959-649f39fa-3364-11e8-9d51-7f74b8330bf5.png)

Invalid selection (Doctrine is not Cadian) without a warning:
![invalid_no_warning](https://user-images.githubusercontent.com/22036809/38093965-6715e22e-3364-11e8-979a-e708bf4abe6c.png)

Invalid selection with warning ("Chainsword" was changed to "Power sword"):
![invalid_with_warning](https://user-images.githubusercontent.com/22036809/38093967-68b68ce6-3364-11e8-85a8-a1eaa93ce996.png)

**Comment by DrTobogganMD** [comment]
Confirmed. Seems like an extension of the old bug that was causing points not to change until refreshing.

**Comment by Jonskichov** [comment]
Fixed in 2.01.11.104 on desktop

Android and iOS builds coming in the next day or so

**Comment by Jonskichov** [comment]
Fixed in 2.01.17.270 on Android

**Comment by Jonskichov** [comment]
Fixed in 2.01.15.113 on iOS
