### ISSUE TITLE
Root Rules links to Shared Rules not displayed in roster view

### ISSUE THREAD

**Issue by afraeve** [BattleScribe/Release#66]
Hi! Where the Root Rules section has links to Shared Rules, either local or in the gst, these are no longer being displayed in the Force Rules section when you view a roster.
For example, make a list using any Space Marine cat from the Epic Armageddon repo - you should see the "Strategy Rating & Initiative" (local) and "They Shall Know No Fear" (from the gst).
I'm using  v2.02.03.124 on Windows 10 desktop, and v2.02.02.298 on Android 8.0

**Comment by Jonskichov** [comment]
Fixed in:
Desktop: 2.02.04
Android: 2.02.03
iOS: 2.02.04

Note that as of writing the iOS version is currently being reviewed by Apple. It should become available for download within 24hrs (roughly).
