### ISSUE TITLE
Crash opening rosters?

### ISSUE THREAD

**Issue by Jonskichov** [BattleScribe/Release#68]
https://battlescribe.uservoice.com/forums/55066-battlescribe/suggestions/37698592-unable-to-open-an-adeptus-astartes-roster

**Comment by Mad-Spy** [comment]
@Jonskichov, the issue occurs when BS compiles the data files to even create a blank Roster, not just when attempting to open existing ones.

**Comment by Jonskichov** [comment]
Most likely due to old large SM data
