### ISSUE TITLE
Data Editor should reload file if dependant file changes

### ISSUE THREAD

**Issue by L3610N115** [BattleScribe/Release#69]
I tend to work with roughly 2-3 files opened at the same time in different windows. One of these files is usually the GST. If I modify something in the GST, I have to save, close and re-open the other files I am working on because there is no "refresh function" like for example my internet browser has on F5.
A refresh function like the roster editor has it would be appreciated.

**Comment by Jonskichov** [comment]
Fixed in 2.03.19.160
