### ISSUE TITLE
2.01.10 for Desktop causes entry choices to cause the entire entry to disappear

### ISSUE THREAD

**Issue by DrTobogganMD** [BattleScribe/Release#7]
See https://github.com/BSData/wh40k/issues/2774 and https://github.com/BSData/wh40k/issues/2775

Not an issue on mobile or 2.01.09, seems like a bug with the new desktop release.

**Comment by GenWilhelm** [comment]
Appears to only be happening when switching from one selection to another within a group that uses radio buttons (ie. max 1 in parent). The parent of the group is removed from the roster along with its selections.

**Comment by Jonskichov** [comment]
Yep was a bug - fixed it the same evening though. Update to 2.01.10.101 (all the ones and zeros...)
