### ISSUE TITLE
Data Editor bugging out when deleting non-localized entries

### ISSUE THREAD

**Issue by L3610N115** [BattleScribe/Release#70]
Out of curiosity I deleted a non-localized entry and BS reacted very weirdly to that. I basically lost control over what was happening and had to close the catalogue I was working on.
Things that occured are:
(1) I could no longer scroll all the way up.
(2) The entry I wanted to delete was still there, marked and I had trouble marking/clicking on other entries.
(3) It copied the entry and pasted it about... 10 times or so. 

![bs bug](https://user-images.githubusercontent.com/47950292/58359295-fdc67200-7e82-11e9-9987-73f196b9ac47.jpg)

![bs bug 2](https://user-images.githubusercontent.com/47950292/58359302-061ead00-7e83-11e9-866b-45f74494fa62.jpg)

**Comment by Jonskichov** [comment]
Fixed in 2.03.19.160
