### ISSUE TITLE
Battle Scribe falsely claims that the file is unsaved and changes the status from saved to unsaved for no reason.

### ISSUE THREAD

**Issue by L3610N115** [BattleScribe/Release#73]
Example: I work on a file, am done and press the save button. It says the file is saved but not incremented which is fine, I do not want to increment it. Now, I click on open new file, to work on another file and in that very moment the "saved" status changes to unsaved and BS asks me if I want to save. This happens regularly but not always. I can't seem to make out why or under which circumstances.

**Comment by Jonskichov** [comment]
Obsolete
