### ISSUE TITLE
Android App does not refresh game system file

### ISSUE THREAD

**Issue by BitPsycho** [BattleScribe/Release#74]
I just released a new version of the 'Kings of War - Vanguard' game sytem - which included various changes in the game system file.

Users reported to me that the newly announced functionality did not work although they had updated the data repo to the latest version (1.40).

I had tested my changes on the desktop app and did not encounter any of the issues they reported.

I had installed BS before on my android phone and had recently updated it to the latest version ( currently have 2.02.03.299 ) so I did the same check:

- updated the game system - which was still on version 1.2
- opened an existing roster

And indeed ... the changes that came with version 1.4 were not applied.  Then I noticed that actually any changes in 1.2 ( like a new roster type ) were not there either.

So it seems that - although the data repository is 'updated' - and the description of the game system is displaying the latest version - the actual game system file was not updated.

The solution so far to get it fixed seems:

- remove the selected game system and make sure the 'delete all data' is marked

- close / restart the app

- add the game system again 

Then all functionality is correctly working ...

Android Nokia 6.1 phone
Android version 9

**Comment by amis92** [comment]
@BitPsycho have you incremented revision of the datafiles you expect to be updated? I'd guess you mean `Vanguard.gst` - it still has revision 1.


BattleScribe, when updating, checks for revision file by file. The file is downloaded/updated only if the revision declared is greater than the local file's.

**Comment by BitPsycho** [comment]
@amis92 Thanks for your quick response.  Indeed I did not update the revision number as I assumed this was the actual 'version' of the game system - which in my case is still '1'.

And like I said ... I never had that issue with the desktop application so there the game system file does get updated - even without a changed 'revision' number - so it seems strange there is a different behavior in that respect between the different OS apps. 

And I neve updated the revision of any of the warband files .. and those do get updated with every release.

**Comment by morvael** [comment]
Maybe you've used "Delete existing data first" option.

**Comment by BitPsycho** [comment]
@Morvael Yeah that could have been an option but I typically don't 

Now having said that I do realize now that I am an exceptional case ofc because I actually have the changed data files already sitting in my folder as I am editing them ..

Will ask a friend to do a check on his computer ...

But I would have expected to receive many complaints from the userbase on missing functionality - I have 10 releases already ... so very weird ...

**Comment by morvael** [comment]
Maybe your userbase uses that option often :)

**Comment by amis92** [comment]
@BitPsycho any suggestion where can we put a reminder to increase the revision in docs? Specifically, catalogue-development wiki?

**Comment by amis92** [comment]
Also, I'm pretty sure the app doesn't differentiate in update behavior between game system files and catalogues. It's all the same.

**Comment by BitPsycho** [comment]
Hahaha ... now I understand why I am getting this pesky 'do you want to update the revision number' popup every time I made a change .... I was about to create a future request to get this popup away as I was thinking the game system version does not change that much ... hmmm now I understand why it is there ...

@amis92 Good point ... I glanced again at the whole WIKI and could not find any info on this revision number ( but then again - I might be willingfully blind as I didn't see it before either :p ) ... Anyways .. I guess the best place would be 'Data Author Guide' no ?  I don't particularly find a good page which is only about using the data roster editor tool ... that's maybe lacking a bit imo.

**Comment by Jonskichov** [comment]
👍
