### ISSUE TITLE
Refresh child elements on parent change

### ISSUE THREAD

**Issue by morvael** [BattleScribe/Release#76]
In my data file child elements alter their cost and/or profiles based on selections in parent element (they must have the same configuration, yet be priced separately). Currently child element cost is updated only on roster load, does not update when changing configuration in roster editor.

**Comment by morvael** [comment]
[test case](https://drive.google.com/open?id=1hD1hmGZRQ3Js0_sR2wvcyeowUGBREtzu)

Open file, change cost of any ship group (Frigates, Cruisers, Strike Carriers in bold), see that the cost doesn't change. Save, reload, see changed cost.

**Comment by Jonskichov** [comment]
Fixed in:
Desktop: 2.03.13.142
Android: 2.03.19.328
iOS: 2.03.11.147
