### ISSUE TITLE
Ancestor check not working in all cases

### ISSUE THREAD

**Issue by morvael** [BattleScribe/Release#77]
Entry - Entry - Profile - Modifier - Condition Group - If Ancestor Instance Of is working.

Entry - Entry - Info Group - Profile - Modifier - Condition Group - If Ancestor Instance Of is not working.

**Comment by morvael** [comment]
[test case](https://drive.google.com/open?id=1hD1hmGZRQ3Js0_sR2wvcyeowUGBREtzu)

Open file, view roster, see that:
- "Cruiser K - NC-3 Missiles" have "(Medium Group 1)" or "(Medium Group 2)" appended to profile name.
- "Cruiser E1 - NC-16 Missile Bank" doesn't have "(Medium Group 1)" or "(Medium Group 2)" appended to profile name.

**Comment by Jonskichov** [comment]
Fixed in:
Desktop: 2.03.13.142
Android: 2.03.19.328
iOS: 2.03.11.147
