### ISSUE TITLE
Stale cost with modifier - Tactical Drones

### ISSUE THREAD

**Issue by amis92** [BattleScribe/Release#78]
Found a bug with modifier updates:

### Repro

1. Take the given files: [wh40k-apocalypse-tau.zip](https://github.com/BattleScribe/Release/files/3330773/wh40k-apocalypse-tau.zip)
2. Create a new roster with 1 Tau force
3. Add Tactical Drones (Fast Attack)
4. Observing PL of `x Models` entries:
  1. check any Gun/Shield/Marker Drone (costs changed)
  2. uncheck any Gun/Shield/Marker Drone (costs returned to basic)
  3. check any Gun/Shield/Marker Drone  (costs changed)
  4. check any other Gun/Shield/Marker Drone (costs same)
  5. uncheck *the first* (first checked) Gun/Shield/Marker Drone (costs same)
  6. uncheck *the second* Gun/Shield/Marker Drone (costs same **for the current** `x Models` selection)

### Expected:

All costs of `x Models` return to normal.

**Comment by amis92** [comment]
Windows 10, BattleScribe v2.02.04.125

**Comment by morvael** [comment]
I find it funny that only the cost of unselected models change, but for those selected it remains unchanged. It might be similar issue to [mine](https://github.com/BattleScribe/Release/issues/76), where a cost of an entry depends on selections in siblings.

BTW, Tactical Drones are under Fast Attack, not Elites.

**Comment by Jonskichov** [comment]
Fixed in:
Desktop: 2.03.13.142
Android: 2.03.19.328
iOS: 2.03.11.147
