### ISSUE TITLE
Modifying Max in Parent Constraint Via Modifier Group Does Not Change Controls

### ISSUE THREAD

**Issue by GenWilhelm** [BattleScribe/Release#79]
Repro:
1. Create a selection entry as a child to another selection entry.
2. Add a constraint of `max 1 Selections in Parent` to the child.
3. Add a modifier group to the child.
4. Add a modifier of `set [max 1 Selections in Parent] to 2` to the modifier group.

Expected:
- The child selection has a spinner control.

Actual:
- The child selection has a checkbox control.

**Comment by Jonskichov** [comment]
Fixed in:
Desktop: 2.03.13.142
Android: 2.03.19.328
iOS: 2.03.11.147
