### ISSUE TITLE
Duplicated Selections - Only Able To Change Original

### ISSUE THREAD

**Issue by GenWilhelm** [BattleScribe/Release#8]
Observed on Desktop v2.01.10.101

When a selection is duplicated, changing any selections within the duplication will affect the original selection instead of the new one. Collective entries within duplicated selections appear to update as expected, but will be reverted upon refreshing the roster.

Refreshing the roster the roster seems to fix the behaviour.

Ref: https://github.com/BSData/wh40k/issues/2807

---

Repro steps:
 - Start a Warhammer 40,000 8th Edition roster
 - Add a force of Imperium - Astra Militarum
 - Under HQ, add a Company Commander
 - Duplicate the Company Commander
 - Change the Chainsword selection to Power Axe
 - Select the other Company Commander
   - Observe how Power Axe is selected, despite the roster saying he has a Chainsword
 - Change the Chainsword selection to Power Fist
   - Observe how the Power Axe on the original Company Commander is changed to a Power Fist
 - Under Troops, add an Infantry Squad
 - Duplicate the Infantry Squad
 - Select the new Infantry Squad
 - Reduce the number of Guardsman selections from 9 to 8
   - Observe how both Infantry Squads both display 8x Guardsman, but only one warning is shown for having too few Guardsmen
 - Select the warning
   - Observe how the original Infantry Squad is now selected as the source of the warning.
 - Save the roster
 - Load the roster
   - Observe how Infantry Squads now display 9x and 8x Guardsman, and selections now behave as expected.

**Comment by Jonskichov** [comment]
Fixed in 2.01.10.102
