### ISSUE TITLE
Issue with Dual Primary Categories

### ISSUE THREAD

**Issue by cartag** [BattleScribe/Release#83]
If an SSE has a primary category set, and the RSE link to it also is set with a primary category, the resulting item will be under uncategorized, even if the primary category is the same. Removing primary category from the RSE makes them show up where they should, but it still seems like a bug. 

For the record, I'm not intentionally setting anything up with both, I'm doing cleanup which sometimes makes bugs show their faces.

**Comment by Jonskichov** [comment]
I set up a small test file with a link with a primary category which links to a SSE with a primary and things appeared to work as expected. I'm guessing something's wrong with that set up.

Do you need to set the _same_ primary category on both?

**Comment by Jonskichov** [comment]
Fixed for the next release

**Comment by Jonskichov** [comment]
Fixed in 2.03.01
