### ISSUE TITLE
Issue loading / creating new roster with drop box

### ISSUE THREAD

**Issue by penguin20000** [BattleScribe/Release#84]
Using BS 2.03 on Android with Dropbox linked whenever i try to open or create a new roster it takes a very very long time. Meanwhile my dropbox app on my PC informs me of new files being created constantly, it looks like backups being created each time?

![image](https://user-images.githubusercontent.com/10774422/63581075-15022200-c58e-11e9-85cc-b2680bd88b6d.png)
![image](https://user-images.githubusercontent.com/10774422/63581096-21867a80-c58e-11e9-963e-e6447e53d1bf.png)
![image](https://user-images.githubusercontent.com/10774422/63581109-2ba87900-c58e-11e9-9c81-ef63fd060137.png)

**Comment by rorold** [comment]
I'm also seeing this issue, still happening in version 2.03.09 after the updates a few days ago.

**Comment by Jonskichov** [comment]
Fixed a while back.
