### ISSUE TITLE
Primary Category Bug - iOS

### ISSUE THREAD

**Issue by cartag** [BattleScribe/Release#87]
An entry set up this way will show up properly on desktop as a Battalion, but on iOS it will show as Uncategorized. I don't think we ever checked if the primary was on the RSE instead of the SSE. 

SSE
![image](https://user-images.githubusercontent.com/4388344/65284366-90f07b00-daf6-11e9-9f62-8be6bfda8927.png)

RSE
![image](https://user-images.githubusercontent.com/4388344/65284390-9f3e9700-daf6-11e9-92cc-f1ac55c540f4.png)

**Comment by Jonskichov** [comment]
Can you confirm if this is still an issue?

**Comment by Jonskichov** [comment]
As far as I can tell, this is no longer an issue

**Comment by Jonskichov** [comment]
Fixed in:
Desktop: 2.03.13.142
Android: 2.03.19.328
iOS: 2.03.11.147
