### ISSUE TITLE
MacOS appbundler doesn't work well with modern Javas

### ISSUE THREAD

**Issue by Floppy** [BattleScribe/Release#92]
Using the appbundler-created download with `JavaAppLauncher` in it left me with an "Unable to load Java Runtime Environment" message, as I don't have the traditional Safari Java plugin installed, and battlescribe doesn't bundle its JRE. However, I replaced it with https://github.com/tofi86/universalJavaApplicationStub, and it worked first time! I suggest that you update your macOS builds to use this instead of the old appbundler :)

**Comment by Jonskichov** [comment]
Obsolete
