### ISSUE TITLE
Android 2.03.06 - Not correctly counting options from nested shared Selection Entry Groups

### ISSUE THREAD

**Issue by Mad-Spy** [BattleScribe/Release#93]
There appears to be a bug in v2.03.06 which is causing items selected in a nested shared selection group to fail to be counted against constraints and/or modifiers.

For example, using the 40k Death Guard catalogue, the entry below for Blightlord Terminators give an immediate error on adding it to a roster.

![image](https://user-images.githubusercontent.com/29306451/67566579-1089ef00-f720-11e9-9fc1-e4d1f5ee8f92.png)

Items selected from the linked "Blightlord Terminator Melee weapons" group are not registering against the "min 2 in Parent" constraint.

**Comment by Jonskichov** [comment]
Fixed in:
- Android 2.03.07.315
- Desktop 2.03.05.133
- iOS 2.03.04.138 (pending Apple approval)

**Comment by Jonskichov** [comment]
Additional bug fixed in:

- Android 2.03.08.316
- Desktop 2.03.06.134
- iOS 2.03.04.139 (pending Apple approval)
