### ISSUE TITLE
If Primary Catalogue Instance Of condition not firing

### ISSUE THREAD

**Issue by Mad-Spy** [BattleScribe/Release#94]
In Warhammer 40,000 8tth Edition.gst, we have the below:

![image](https://user-images.githubusercontent.com/29306451/67750392-0836fa00-fa27-11e9-82b6-7ae2e300aa18.png)

This option is not getting made visible when loaded into one of the listed Catalogues.

This is happening in Android 2.03.09.317 and PC 2.04.06.134

**Comment by Jonskichov** [comment]
Fixed in:
Android: 2.03.15.323
Desktop: 2.03.09.137
iOS: Pending

**Comment by Jonskichov** [comment]
Fixed in:
iOS: 2.03.06.141
