### ISSUE TITLE
Validation error in V2.03.06.134

### ISSUE THREAD

**Issue by Dragacane** [BattleScribe/Release#96]
I'm getting an error when selecting more then one relic (Signature System for Tau) even when using the ability to take more than one relic.
When more than one relic is equipped in the lower part of Battlescribe will repeat many times that I've selected too many relics
![Battlescribe](https://user-images.githubusercontent.com/57176620/67850496-9bbe1700-fb5c-11e9-9a1a-2cdbd69c54e4.PNG)

**Comment by Jonskichov** [comment]
Fixed in:

Android: 2.03.12.320
Desktop: 2.03.07.135
iOS: Pending (hopefully I'll get it done and uploaded tomorrow)

**Comment by Jonskichov** [comment]
Fixed in iOS 2.03.05.140 (awaiting Apple review)
