### ISSUE TITLE
2.03: validation regression bug

### ISSUE THREAD

**Issue by amis92** [BattleScribe/Release#97]
Essentially #43 again.

**Comment by amis92** [comment]
Reported for T'au in https://github.com/BSData/wh40k/issues/5924

**Comment by amis92** [comment]
Confirmed on PC v2.03.06

**Comment by Jonskichov** [comment]
Fixed in:

Android: 2.03.12.320
Desktop: 2.03.07.135
iOS: Pending (hopefully I'll get it done and uploaded tomorrow)

**Comment by Jonskichov** [comment]
Fixed in iOS 2.03.05.140 (awaiting Apple review)
