### ISSUE TITLE
Data Editor: Working condition's Child ID disappears

### ISSUE THREAD

**Issue by amis92** [BattleScribe/Release#98]
Using v2.03.06 on Desktop.

Maybe related to #85, maybe not.

There's a working condition (checked in Roster Editor). As soon as I focus on it, the Child "disappears".

Before focusing:

![image](https://user-images.githubusercontent.com/2671396/68104642-22b41c00-fedc-11e9-9bc1-653ed5c7b1d0.png)

After focusing:

![image](https://user-images.githubusercontent.com/2671396/68104652-32cbfb80-fedc-11e9-82f1-9d8ed09644c2.png)

Data files used:

[repro.zip](https://github.com/BattleScribe/Release/files/3802932/repro.zip)

**Comment by Mad-Spy** [comment]
This is because you cannot select an SSE as the target of a condition within an SSEG without directly editing the XML. SSEs don't appear in the dropdown. The Editor doesn't understand what has been done here and deletes it as invalid.

**Comment by Jonskichov** [comment]
Fixed in:

Android: 2.03.12.320
Desktop: 2.03.07.135
iOS: Pending (hopefully I'll get it done and uploaded tomorrow)

**Comment by Jonskichov** [comment]
Fixed in iOS 2.03.05.140 (awaiting Apple review)
