### ISSUE TITLE
v2.03 Condition not working (regression)

### ISSUE THREAD

**Issue by amis92** [BattleScribe/Release#99]
There's an issue with conditions across the board not working correctly.

One example is a https://github.com/bsdata/wh40k/issues/5945

For many cases it seems the problem is when a condition has an EntryLink as the child (Filter By). When conditions are changed to the Entry itself, they start working. It's not a practical approach though, because there are legit cases where the Link itself is needed, the linked issue being such a case.

And obviously, that has been working - before the latest memory optimization update.

**Comment by Jonskichov** [comment]
Fixed in:

Android: 2.03.12.320
Desktop: 2.03.07.135
iOS: Pending (hopefully I'll get it done and uploaded tomorrow)

**Comment by Jonskichov** [comment]
Fixed in iOS 2.03.05.140 (awaiting Apple review)
